apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
spec:
  volumes:
  - name: shared-volume
    emptyDir: {}

  containers:
  - name: alpine-container-1
    image: alpine:3.12.0
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - name: shared-volume
      mountPath: /etc/a

  - name: alpine-container-2
    image: alpine:3.12.0
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - name: shared-volume
      mountPath: /etc/b